const DOCS_RESPONSIVE_BREAKPOINT = 760;
const DOCS_RESPONSIVE_BREAKPOINT_PX = "760px";
const DOCS_PATH_NAME = "docs";
const SCROLL_SPY_ROOT_ELEMENT = "docs-content";

module.exports = {
  DOCS_RESPONSIVE_BREAKPOINT,
  DOCS_RESPONSIVE_BREAKPOINT_PX,
  DOCS_PATH_NAME,
  SCROLL_SPY_ROOT_ELEMENT,
};
