const DOCS_RESPONSIVE_BREAKPOINT = 760;
const DOCS_RESPONSIVE_BREAKPOINT_PX = "760px";
const DOCS_PATH_NAME = "docs";

module.exports = {
  DOCS_RESPONSIVE_BREAKPOINT,
  DOCS_RESPONSIVE_BREAKPOINT_PX,
  DOCS_PATH_NAME,
};
