import { library, config } from "@fortawesome/fontawesome-svg-core";
import {
  faExternalLinkAlt,
  faCloudDownloadAlt,
  faAnchor,
  faTags,
  faArrowUp,
  faArrowLeft,
  faArrowRight,
  faBook,
  faBars,
  faTimes,
  faLink,
  faSlidersH,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faSearch,
  faQuestionCircle,
  faRss,
} from "@fortawesome/free-solid-svg-icons";
import {
  faEdit,
  faCopy,
  faCalendarAlt,
} from "@fortawesome/free-regular-svg-icons";
import {
  faTwitter,
  faLinkedinIn,
  faGithub,
  faSlack,
  faYoutube,
  faStackOverflow,
} from "@fortawesome/free-brands-svg-icons";

config.autoAddCss = false;

library.add(
  faExternalLinkAlt,
  faCloudDownloadAlt,
  faCalendarAlt,
  faAnchor,
  faLink,
  faTags,
  faArrowUp,
  faArrowLeft,
  faArrowRight,
  faSlidersH,
  faBook,
  faBars,
  faTimes,
  faSearch,
  faQuestionCircle,
  faEdit,
  faCopy,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faTwitter,
  faLinkedinIn,
  faGithub,
  faSlack,
  faYoutube,
  faStackOverflow,
  faRss,
);
